x-postgres-common: &postgres-common
  image: postgres:latest
  environment:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    TZ: "Asia/Tokyo"
  command: [ "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
  healthcheck:
    test: pg_isready -h localhost -d postgres -U postgres
    interval: 20s
    timeout: 5s
    retries: 3
  restart: always

services:
  db_primary:
    <<: *postgres-common
    hostname: db_primary
    container_name: db_primary
    ports:
      - 15432:5432
    volumes:
      - ./db_primary/sql:/docker-entrypoint-initdb.d
      - ./db_primary/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./db_primary/conf/postgresql.conf:/etc/postgresql/postgresql.conf

  db_replica:
    <<: *postgres-common
    hostname: db_replica
    container_name: db_replica
    ports:
      - 25432:5432
    volumes:
      - ./db_replica/sql:/docker-entrypoint-initdb.d
      - ./db_replica/scripts/entrypoint.sh:/entrypoint.sh
      - ./db_replica/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./db_replica/conf/postgresql.conf:/etc/postgresql/postgresql.conf
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      db_primary:
        condition: service_healthy
